import type { NextPage } from 'next'
import Head from 'next/head'
import { useMachine } from '@xstate/react'
import { assign } from 'xstate'
import TicTacToeMachine from '../Machine/TicTacToeMachine'
import { Container, MainContainer, PlayerText, Tile } from '../styles/tictactoe.styled'

const Home: NextPage = () => {

  const range = (start:number,end:number) => {
    return Array(end-start).fill(null).map((_,i) => i + start)
  }
  const [current, send] = useMachine(TicTacToeMachine);

  const cellClickHandler = () => {
    send("click");
    console.log(current.context.currentPlayer);
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer >
        <PlayerText>Player {current.context.currentPlayer.toUpperCase()}</PlayerText>
        <Container >
          {range(0, 9).map(i => (
            <Tile
              onClick={cellClickHandler}
              data-player={current.context.cells[i]}
              key={i}
            />
          ))}
        </Container>
      </MainContainer>
    </div>
  )
}

export default Home
