import type { NextPage } from 'next';
import Head from 'next/head';
import { useMachine } from '@xstate/react';
import TicTacToeMachine from '../Machine/TicTacToeMachine';
import { Container, MainContainer, PlayerText, ResetButton, Tile, WinnerText } from '../styles/tictactoe.styled';

const Home: NextPage = () => {
  const range = (start: number, end: number) => {
    return Array(end - start)
      .fill(null)
      .map((_, i) => i + start);
  };
  const [current, send] = useMachine(TicTacToeMachine);
  console.log(current);

  const cellClickHandler = (i: number) => {
    send({
      type: 'click',
      clickedCell: i
    });
    console.log(current.context.currentPlayer);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <PlayerText>Player {current.context.currentPlayer.toUpperCase()}</PlayerText>
        <ResetButton onClick={() => send('RESET')}>Reset</ResetButton>
        <Container>
          {range(0, 9).map((i) => (
            <Tile
              onClick={() => cellClickHandler(i)}
              data-player={current.context.cells[i]}
              key={i}
            />
          ))}
        </Container>
        <WinnerText style={{ color: 'red' }}>The winner is:{current.context.winner?.toUpperCase()}</WinnerText>
      </MainContainer>
    </div>
  );
};

export default Home;
